### PR TITLE
Fixes #3 - Uncaught exception when WebSocketSend called after WS closed.

### LINKED ISSUE #3: Uncaught exception when WebSocketSend called after WS closed
An uncaught exception will occur if `WebSocketSend` is called after the `ws` property on the instance has already been deleted here: https://github.com/jirihybek/unity-websocket-webgl/blob/master/Plugins/WebSocket.jslib#L205

```
Uncaught TypeError: Cannot read property 'readyState' of undefined
```

This is because the `WebSocketSend` method only checks for `null`, but in this case the value would be `undefined` here: https://github.com/jirihybek/unity-websocket-webgl/blob/master/Plugins/WebSocket.jslib#L258

I will have a PR with the fix momentarily.

### PR DESCRIPTION
**Pull request by austinkelleher**
Fixes #3

### CODE REVIEW

**Comment by austinkelleher** [comment]
@jirihybek Any interest in merging this?

**Comment by johnou** [comment]
@jirihybek ptal

**Comment by XtroTheArctic** [comment]
This PR fixed my problem. Thank you very much.

**Comment by austinkelleher** [comment]
Spring cleaning on open PRs. 😬 Closing due to project inactivity, but I still think this is a valid change.

**Pull request closed without merging**
